Attribute VB_Name = "Module1"

Public Const ID_TAB_TRANSACTION = 130 'ok
Public Const ID_TAB_REPORT = 132
Public Const ID_TAB_MAINTENANCE = 133 '0k
Public Const ID_TAB_UTILITIES = 131 'ok
Public Const ID_TAB_TOOLS = 134
Public Const ID_TAB_WINDOWSETTINGS = 135
Public Const ID_TAB_SYSTEMLOCK = 136

Public Const ID_GROUP_TRANSACTION = 137
Public Const ID_GROUP_REPORT = 138
Public Const ID_GROUP_MAINTENANCE = 139   'ok
Public Const ID_GROUP_DRAWER = 140
Public Const ID_GROUP_TOOLS = 141
Public Const ID_GROUP_WINDOWSETTINGS = 142
Public Const ID_GROUP_SYSTEMLOCK = 143

Public Const ID_VIEW_STATUS_BAR = 2808
Public Const ID_GROUP_PAGESETUP = 5022
Public Const ID_SYSTEM_ICON = 1200
Public Const ID_GROUP_POPUPICON = 2004


Public Const ID_APP_ABOUT = 4000
Public Const ID_MAINTENANCE_USER_CHANGEPASS = 4001 'ok
Public Const ID_MAINTENANCE_USER_LIST = 4010

Public Const ID_MAINTENANCE_DISCPENALTIES = 4002 'ok
Public Const ID_MAINTENANCE_DISCRENTALRATE = 4003  'ok
Public Const ID_MAINTENANCE_DISCRENTPERIOD = 4004 'ok
Public Const ID_MAINTENANCE_MODIFYMEMBERS = 4005  'ok
Public Const ID_MAINTENANCE_MEMBERPAYMENT = 4006



Public Const ID_PRODUCT_ENTRY = 4008
Public Const ID_PRODUCT_RENT = 4009
Public Const ID_PRODUCT_RETURN = 4010
Public Const ID_PRODUCT_ADDEXISTING = 4011
Public Const ID_PRODUCT_NEWMEMBER = 4012


Public Const ID_TRANSACTION_RENT = 4013
Public Const ID_TRANSACTION_RETURN = 4014


Public Const ID_INVENTORY_LISTCD = 4021
Public Const ID_INVENTORY_LISTMEMBERS = 4022
Public Const ID_INVENTORY_UNRETURNCD = 4023

Public Const ID_REPORT_INCOME = 4030
Public Const ID_REPORT_AUDITTRAIL = 4031
Public Const ID_REPORT_LOGHISTORY = 4032

Public Const ID_TOOLS_NOTEPAD = 4033
Public Const ID_TOOLS_CALCULATOR = 4034
Public Const ID_TOOLS_ARCHIVE = 4035
Public Const ID_TOOLS_BACKUP = 4036

Public Const ID_WINDOWSETTINGS_THEMES = 4037

Public Const ID_SYSTEMLOCK_LOCK = 4038



Public Const ID_APP_LOGOUT = 57665




